"""Extract face-reading traits from a photo using the Ollama vision API.

Uses the same Ollama deployment as the chat service (Gemma 3 is natively
multimodal; ``llava`` and ``moondream`` also work if the operator prefers
them via ``OLLAMA_VISION_MODEL``).

We ask the model for a STRICT JSON object mapping each of the 10 face
features to one of our enum values, then clamp any out-of-vocab returns
back to a safe default. The calling endpoint hands the result straight to
``analyse_face()`` — the narrative is still generated by the deterministic
rule engine, never the LLM, so we don't hallucinate readings.
"""

from __future__ import annotations

import json
import os
import re
from urllib import error, request

OLLAMA_BASE_URL = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
OLLAMA_VISION_MODEL = os.environ.get(
    "OLLAMA_VISION_MODEL", os.environ.get("OLLAMA_MODEL", "gemma3:4b")
)
OLLAMA_TIMEOUT_SEC = float(os.environ.get("OLLAMA_TIMEOUT_SEC", "120"))

FACE_PROMPT = """You are an expert in Chinese physiognomy (面相). Look at the face photo and
identify exactly 10 features. Respond with ONLY a JSON object, no prose, no
code fences, no explanation.

{
  "face_shape":  one of "round" | "square" | "oval" | "long" | "heart" | "diamond",
  "forehead":    one of "high" | "medium" | "low" | "narrow" | "wide",
  "brows":       one of "thick" | "medium" | "thin" | "arched" | "straight",
  "eyes":        one of "big" | "medium" | "small" | "phoenix" | "deep",
  "nose":        one of "straight" | "high" | "flat" | "hooked" | "small",
  "mouth":       one of "full" | "medium" | "thin" | "wide" | "small",
  "ears":        one of "large" | "medium" | "small" | "attached" | "detached",
  "chin":        one of "strong" | "rounded" | "pointed" | "double" | "receding",
  "cheeks":      one of "high" | "full" | "flat" | "hollow",
  "skin":        one of "bright" | "neutral" | "dull" | "ruddy"
}

Rules:
- Pick EXACTLY one value from each list.
- If you are unsure, pick the closest match — never leave a field blank.
- Output JSON ONLY. No commentary before or after.
"""

FACE_ALLOWED: dict[str, list[str]] = {
    "face_shape": ["round", "square", "oval", "long", "heart", "diamond"],
    "forehead":   ["high", "medium", "low", "narrow", "wide"],
    "brows":      ["thick", "medium", "thin", "arched", "straight"],
    "eyes":       ["big", "medium", "small", "phoenix", "deep"],
    "nose":       ["straight", "high", "flat", "hooked", "small"],
    "mouth":      ["full", "medium", "thin", "wide", "small"],
    "ears":       ["large", "medium", "small", "attached", "detached"],
    "chin":       ["strong", "rounded", "pointed", "double", "receding"],
    "cheeks":     ["high", "full", "flat", "hollow"],
    "skin":       ["bright", "neutral", "dull", "ruddy"],
}

_SAFE_DEFAULTS: dict[str, str] = {
    "face_shape": "oval",
    "forehead":   "medium",
    "brows":      "medium",
    "eyes":       "medium",
    "nose":       "straight",
    "mouth":      "medium",
    "ears":       "medium",
    "chin":       "rounded",
    "cheeks":     "full",
    "skin":       "neutral",
}


def _strip_data_url(b64: str) -> str:
    """If given a 'data:image/jpeg;base64,AAAA…' string, return just the base64
    bytes after the comma. Ollama wants raw base64 in its ``images`` array."""
    if b64.startswith("data:"):
        comma = b64.find(",")
        if comma != -1:
            return b64[comma + 1:]
    return b64


_JSON_OBJ_RE = re.compile(r"\{[^{}]*\}", re.S)


def _parse_json_loose(text: str) -> dict:
    """Pull a JSON object out of an LLM reply that may have stray text or
    code-fence markers."""
    text = text.strip()
    # Strip common fence wrappers.
    if text.startswith("```"):
        # strip first fence line + trailing fence
        text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)
    try:
        return json.loads(text)
    except Exception:
        pass
    # Scan for any braces-balanced object.
    for m in _JSON_OBJ_RE.findall(text):
        try:
            return json.loads(m)
        except Exception:
            continue
    raise ValueError(f"No JSON object in vision reply: {text[:200]!r}")


def _call_ollama_vision(prompt: str, image_b64: str) -> str:
    payload = {
        "model": OLLAMA_VISION_MODEL,
        "messages": [
            {"role": "user", "content": prompt, "images": [_strip_data_url(image_b64)]},
        ],
        "stream": False,
        "options": {"temperature": 0.1, "num_ctx": 4096},
    }
    body = json.dumps(payload).encode("utf-8")
    url = OLLAMA_BASE_URL.rstrip("/") + "/api/chat"
    req = request.Request(
        url, data=body, headers={"Content-Type": "application/json"}, method="POST"
    )
    try:
        with request.urlopen(req, timeout=OLLAMA_TIMEOUT_SEC) as resp:
            data = json.loads(resp.read().decode("utf-8"))
    except error.URLError as exc:
        raise RuntimeError(
            f"Cannot reach Ollama at {OLLAMA_BASE_URL}. "
            "Deploy an Ollama service with a vision-capable model "
            "(gemma3:4b, llava, moondream) and set OLLAMA_VISION_MODEL."
        ) from exc
    except TimeoutError as exc:
        raise RuntimeError(
            "Vision analysis timed out. On CPU-only Ollama this is slow — try "
            "a smaller model (moondream) or bump OLLAMA_TIMEOUT_SEC."
        ) from exc
    msg = data.get("message", {}).get("content", "")
    if not msg:
        raise RuntimeError(f"Ollama returned an empty vision reply: {data}")
    return msg.strip()


def extract_face_traits(image_b64: str) -> dict[str, str]:
    """Return a dict with all 10 trait keys, each clamped to a legal enum value."""
    raw = _call_ollama_vision(FACE_PROMPT, image_b64)
    try:
        data = _parse_json_loose(raw)
    except Exception as exc:
        raise RuntimeError(f"Vision reply was not valid JSON: {raw[:200]}") from exc

    out: dict[str, str] = dict(_SAFE_DEFAULTS)
    for key, allowed in FACE_ALLOWED.items():
        val = data.get(key)
        if isinstance(val, str) and val.strip().lower() in allowed:
            out[key] = val.strip().lower()
    return out
